version: "3"

services:
  
  nginx:
    image: nginx
    depends_on: 
      - shock-ui
      - shock-api
      - auth-db

    ports:
      - 8040:8080
      - 8041:80
    volumes:
      - ${PWD}/dev/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}/dev/nginx/:/usr/share/nginx/html/

  shock-ui:
    image: mgrast/shock-browser:demo 
    depends_on:
      - shock-api
      - auth-server
    volumes:
      - ${PWD}/dev/config/shock-browser-config.js:/usr/share/nginx/html/js/config.js 

  shock-api:
    image: mgrast/shock:latest
    depends_on:
      - shock-mongo
    links:
      - shock-mongo:mongo    

  shock-mongo:
    image: mongo        

  adminer:
    image: adminer
    ports:
      - 8043:8080
    depends_on: 
      - auth-db
    links:
      - auth-db:db  

  auth-db:
    image: mysql:5.7
    command: ['--explicit_defaults_for_timestamp', '--init-file', '/tmp/auth-db.mysql']
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: AuthAppUsers
      MYSQL_USER: authService
      MYSQL_PASSWORD: authServicePassword
#      MYSQL_HOST: localhost
    volumes:
      - auth-db:/var/lib/mysql
      - ./dev/config/setup-auth-db.sh:/usr/local/bin/setup-auth-db.sh
      - ./dev/config/auth-db.mysql:/tmp/auth-db.mysql
#    command: /usr/local/bin/setup-auth-db.sh 

  auth-server:
    image: mgrast/authserver:develop
    depends_on:
      - auth-db
    environment:
      MYSQL_HOST: auth-db
      MYSQL_DATABASE: AuthAppUsers
      MYSQL_USER: authService
      MYSQL_PASSWORD: authServicePassword
    ports:
      - 8042:80   
    volumes:
      - ./dev/config/auth-server-httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./../Skyport2/Config/authServer/cgi/:/usr/local/apache2/htdocs/cgi-bin/  
      - ./dev/config/OAuthConfig.pm:/usr/local/apache2/htdocs/cgi-bin/OAuthConfig.pm

  # auth-api:
  #   image: mgrast/authserver:demo
  #   depends_on:
  #     - auth-db
    
  # auth-ui:
  #   image: mgrast/authserver:demo
  #   depends_on:
  #     - auth-db
        

  sequence-center:
    image: mgrast/seqcenter:local
    build: ./

  sequence-center-ui:
    image: mgrast/seqcenter:latest
    depends_on: 
      - auth-server
    volumes:
      - ./dev/config/sequence-center.conf:/usr/local/apache2/conf/httpd.conf  


  sequence-center-api:
    image: mgrast/seqcenter:latest
    depends_on:
      - auth-server

volumes:
  auth-db:
